
cc_library(
    name = 'pebble_rpc_transport',
    srcs = [
               'transport_exception.cpp',
               'msg_buffer.cpp',
			   'buffer_transport.cpp',
    ],
    incs = [
        '../../../deps/tsf4g/include/',
    ],
    deps = [
        '//source/rpc/common:pebble_rpc_common'
    ]
)

