cc_library(
    name = 'pebble_zookeeper',
    srcs = [
        'naming_handler.cpp',
        'zookeeper_cache.cpp',
        'zookeeper_client.cpp',
        'zookeeper_log.cpp',
        'zookeeper_naming.cpp',
    ],
    incs = [
    ],
    deps = [
        '//src/common/:pebble_common',
        '//thirdparty/zookeeper:zookeeper_st',
    ],
)
