cc_binary(
    name = 'message_server',
    srcs = [
        'message_server.cpp',
    ],
    incs = [
        '../../source/message/',
    ],
    deps = [
        '//source/message:pebble_message',
    ]
)

cc_binary(
    name = 'message_client',
    srcs = [
        'message_client.cpp',
    ],
    incs = [
        '../../source/message/',
    ],
    deps = [
        '//source/message:pebble_message',
    ]
)

