
cc_library(
    name = 'pebble_rpc_common',
    srcs = [
               'common.cpp',
               'rpc_error_info.cpp',
               'field_pack.cpp'
    ],
    incs = [
    ],
    deps = [
        
    ]
)

