
cc_library(
    name = 'pebble_dr',
    srcs = [
        'serialize.cpp',
        'common/field_pack.cpp',
        'protocol/base64_utils.cpp',
        'protocol/json_protocol.cpp',
        'protocol/rapidjson_protocol.cpp',
        'protocol/bson_protocol.cpp',
        'transport/transport_exception.cpp',
        'transport/buffer_transport.cpp',
    ],
    incs = [
    ],
    deps = [
    ],
)
