cc_library(
    name = 'pebble_redis',
    srcs = [
        'redis_co.cpp',
    ],
    incs = [
        '../../../thirdparty/hiredis/',
    ],
    deps = [
        '//src/common/:pebble_common',
    ],
)
