#lex_yacc_library(
#    name = 'parser',
#    srcs = [
#        'thriftl.ll',
#        'thrifty.yy'	
#    ],
#    deps = [
#        
#    ]
#)

cc_binary(
    name = 'pebble',
    srcs = [
        'main.cc',
        'thriftl.cc',
        'thrifty.cc',
        'md5.c',
        'parse/t_typedef.cc',
        'parse/parse.cc',
        'generate/t_as3_generator.cc',
        'generate/t_cocoa_generator.cc',
        'generate/t_cpp_generator.cc',
        'generate/t_csharp_generator.cc',
        'generate/t_c_glib_generator.cc',
        'generate/t_delphi_generator.cc',
        'generate/t_d_generator.cc',
        'generate/t_erl_generator.cc',
        'generate/t_generator.cc',
        'generate/t_go_generator.cc',
        'generate/t_gv_generator.cc',
        'generate/t_hs_generator.cc',
        'generate/t_html_generator.cc',
        'generate/t_javame_generator.cc',
        'generate/t_java_generator.cc',
        'generate/t_json_generator.cc',
        'generate/t_js_generator.cc',
        'generate/t_lua_generator.cc',
        'generate/t_ocaml_generator.cc',
        'generate/t_perl_generator.cc',
        'generate/t_php_generator.cc',
        'generate/t_py_generator.cc',
        'generate/t_rb_generator.cc',
        'generate/t_st_generator.cc',
        'generate/t_xsd_generator.cc'
    ],
    incs = [
        '../',
    ],
    deps = [
        
    ]
)
