
cc_library(
    name = 'pebble_rpc_protocol',
    srcs = [
               'base64_utils.cpp',
               'debug_protocol.cpp',
               'dense_protocol.cpp',
               'json_protocol.cpp',
               'bson_protocol.cpp',
               'multiplexed_protocol.cpp',
               'group_protocol.cpp',
    ],
    incs = [
        '../common/',
        '../transport',
    ],
    deps = [
    ]
)

